#wget https://genericwitticism.com:8000/img/skeleton.png
#wget https://genericwitticism.com:8000/img/kobold.png
#wget https://genericwitticism.com:8000/img/ghoul.png
#wget https://genericwitticism.com:8000/img/goblin.png
#wget https://genericwitticism.com:8000/img/ogre.png
#wget https://genericwitticism.com:8000/img/black-pudding.png
#wget https://genericwitticism.com:8000/img/orc.png
#wget https://genericwitticism.com:8000/img/purple-worm.png
#wget https://genericwitticism.com:8000/img/hell-hound.png
#wget https://genericwitticism.com:8000/img/berserker.png
#wget https://genericwitticism.com:8000/img/gelatin-cube.png
#wget https://genericwitticism.com:8000/img/zombie.png
#wget https://genericwitticism.com:8000/img/troll.png
#wget https://genericwitticism.com:8000/img/displacer-beast.png
#wget https://genericwitticism.com:8000/img/hobgoblin.png
#wget https://genericwitticism.com:8000/img/stone-giant.png
#wget https://genericwitticism.com:8000/img/gargoyle.png
#wget https://genericwitticism.com:8000/img/bugbear.png
#wget https://genericwitticism.com:8000/img/carrion-crawler.png

wget https://genericwitticism.com:8000/img/ring.png
wget https://genericwitticism.com:8000/img/armor.png
wget https://genericwitticism.com:8000/img/potion.png
wget https://genericwitticism.com:8000/img/weapon.png
wget https://genericwitticism.com:8000/img/book.png
wget https://genericwitticism.com:8000/img/other-character.png
wget https://genericwitticism.com:8000/img/default-item.png
